// ============================================================================
// Hyaku Asura — Combat Data (authoritative export)
// Source: game.ServerScriptService.Modules.CombatCalcsData (live place)
// Exported: 2026-08-18 (from live CombatCalcsData, studio place [KickBoxing] Hyaku Asura)
// NOTE: Re-export this file from the live module whenever CombatCalcsData changes.
// Do NOT hand-edit these values as a second manual source of truth.
// ============================================================================

window.HYAKU_DATA = {
  // Bump this whenever the live CombatCalcsData is re-exported so old share
  // links can be flagged as stale. Displayed in the "Data health" note.
  DATA_VERSION: "2026-08-18",

  // -- CombatCalculation constants (module top) --
  constants: {
    M1Bonus: 3.5,
    M2Bonus: 3.9,
    SkillBonus: 6,
    M2GlobalMultiplier: 1.12,

    StrEffPenaltyStartMuscle: 1000,
    StrEffPenaltyKneeMuscle: 4000,
    StrEffPenaltyCapMuscle: 7000,
    StrEffPenaltyAtKnee: 0.14,
    StrEffPenaltyAtCap: 0.18,

    LeanBonus: 3,
    LeanStrengthBonus: 0.45,
    LeanCriticalBonus: 1,

    MuscleStrengthNerfCap: 0.1,
    MuscleStrengthNerfRef: 7000,

    MuscleDRCap: 0.18,
    MuscleDRRef: 6000,
    FatDRCap: 0.09,
    FatDRRef: 2000,

    AttackSpeedRawCap: 6500,
    AttackSpeedASMaxBonus: 1.55,
    AttackSpeedLeanCap: 500,
    AttackSpeedMaxMuscleScale: 6000,
    AttackSpeedMaxFatScale: 2000,
    AttackSpeedMaxSizePenalty: 0.85,
    AttackSpeedMaxFatExtraPenalty: 0.25,
    AttackSpeedMaxMuscleExtraPenalty: 0.18,
    AttackSpeedASBonusBulkDampen: 0.62,
    AttackSpeedBulkStyleFloorDrop: 0.72,
    AttackSpeedMaxFinalSpeed: 2.5,
    AttackSpeedMinFinalSpeed: 1,

    AttackSpeedMaxStunReduction: 0.4,
    RhythmMaxStamReduction: 0.3,
    SkillLandedDiscount: 0.3,
  },

  // -- CombatCalculation.StatLimits --
  statLimits: {
    // Synced to live CombatCalculation.StatLimits, 2026-08-15.
    Strength: [
      { Max: 1000, Mult: 1.0 },
      { Max: 1500, Mult: 0.8 },
      { Max: 2000, Mult: 0.65 },
      { Max: 2500, Mult: 0.6 },
      { Max: 3500, Mult: 0.45 },
      { Max: 4500, Mult: 0.3 },
      { Max: 6000, Mult: 0.15 },
      { Max: Infinity, Mult: 0.05 },
    ],
    Muscle: [
      { Max: 500, Mult: 1.0 },
      { Max: 1500, Mult: 0.65 },
      { Max: 2500, Mult: 0.5 },
      { Max: 3500, Mult: 0.45 },
      { Max: 4500, Mult: 0.3 },
      { Max: 6000, Mult: 0.15 },
      { Max: Infinity, Mult: 0.05 },
    ],
    Agility: [
      { Max: 1000, Mult: 1.0 },
      { Max: 1500, Mult: 0.55 },
      { Max: 2000, Mult: 0.4 },
      { Max: 2500, Mult: 0.25 },
      { Max: 3000, Mult: 0.1 },
      { Max: Infinity, Mult: 0.01 },
    ],
    AttackSpeed: [
      { Max: 1500, Mult: 1.0 },
      { Max: 2000, Mult: 0.55 },
      { Max: 2500, Mult: 0.2 },
      { Max: 3000, Mult: 0.05 },
      { Max: Infinity, Mult: 0.01 },
    ],
    Durability: [
      { Max: 2000, Mult: 1.0 },
      { Max: 3000, Mult: 0.5 },
      { Max: 3500, Mult: 0.4 },
      { Max: 4000, Mult: 0.35 },
      { Max: 5000, Mult: 0.2 },
      { Max: 5500, Mult: 0.1 },
      { Max: Infinity, Mult: 0.1 },
    ],
    StaminaInStat: [
      { Max: 1500, Mult: 1.0 },
      { Max: 2500, Mult: 0.7 },
      { Max: 3500, Mult: 0.6 },
      { Max: 4500, Mult: 0.5 },
      { Max: 5500, Mult: 0.4 },
      { Max: 6500, Mult: 0.3 },
      { Max: 7500, Mult: 0.15 },
      { Max: 7500, Mult: 0 },
    ],
    Fat: [
      { Max: 300, Mult: 1.0 },
      { Max: 1000, Mult: 0.5 },
      { Max: 3000, Mult: 0.1 },
      { Max: 10000, Mult: 0.03 },
      { Max: Infinity, Mult: 0.005 },
    ],},
  // -- CombatCalcsData.Styles --
  styles: {
    Basic: {
      M1RangeMul: 1, BaseStun: 0.4, BaseDamageM1: 5, BaseDamageM2: 8.5,
      M1Range: "Average", M2Range: "Above Average", MaxCombo: 4, ComboLife: 1.3,
      M1ComboCooldowns: [0, 0, 0, 1.3], M1ComboLifes: [1.3, 1.3, 1.3, 1.4], M1Speed: 0.9, M2Speed: 0.9,
      M1StaminaCost: 30, M2StaminaCost: 40, M2Cooldown: 2.4, M1Endlag: 0.1,
      M2Endlag: 0.4, Endlag: 0.7, StrengthScaling: 0.75, UpperMuscleScaling: 3,
      LowerMuscleScaling: 3, FatScaling: 0.1, AgilityScaling: 0, AttackSpeedScaling: 0,
      MaxAttackSpeedScale: 0.8, M2MaxAttackSpeedScale: 0.75,
      StaminaScaling: { AttackSpeed: 25, Strength: 30, Muscle: 40, Fat: 40 },
      StaminaScalingCap: { Strength: 60 },
    },
    Kung_Fu: {
      M1RangeMul: 1, BaseStun: 0.42, BaseDamageM1: 5.3, BaseDamageM2: 8.5,
      M1Range: "Average", M2Range: "Above Average", MaxCombo: 4, ComboLife: 1.3,
      M1ComboCooldowns: [0, 0, 0, 1.3], M1ComboLifes: [1.3, 1.3, 1.3, 1.4], M1Speed: 0.8, M2Speed: 0.7,
      M1StaminaCost: 30, M2StaminaCost: 40, M2Cooldown: 2.4, M1Endlag: 0.1,
      M2Endlag: 0.4, Endlag: 0.7, StrengthScaling: 0.75, UpperMuscleScaling: 3,
      LowerMuscleScaling: 3, FatScaling: 0.1, AgilityScaling: 0, AttackSpeedScaling: 0,
      MaxAttackSpeedScale: 0.8, M2MaxAttackSpeedScale: 0.8,
      StaminaScaling: { AttackSpeed: 25, Strength: 30, Muscle: 40, Fat: 40 },
      StaminaScalingCap: { Strength: 60 },
    },
    Aikido: {
      M1RangeMul: 0.98, BaseStun: 0.475, BaseDamageM1: 14.5, BaseDamageM2: 15.5,
      M1Range: "Average", M2Range: "Above Average", MaxCombo: 4, ComboLife: 1.3,
      M1ComboCooldowns: [0, 0, 0, 1.3], M1ComboLifes: [1.3, 1.3, 1.3, 1.4], M1Speed: 1, M2Speed: 1,
      M1StaminaCost: 33.5, M2StaminaCost: 42.5, M2Cooldown: 2.4, M1Endlag: 0.08,
      M2Endlag: 0.4, Endlag: 0.7, StrengthScaling: 0.7, UpperMuscleScaling: 2.2,
      LowerMuscleScaling: 2.2, FatScaling: 0.02, AgilityScaling: 0, AttackSpeedScaling: 0,
      MaxAttackSpeedScale: 0.8, M2MaxAttackSpeedScale: 0.75,
      StaminaScaling: { AttackSpeed: 25, Strength: 30, Muscle: 40, Fat: 40 },
      StaminaScalingCap: { Strength: 60 },
    },
    Jujutsu: {
      M1RangeMul: 0.98, BaseStun: 0.475, BaseDamageM1: 14.8, BaseDamageM2: 16,
      M1Range: "Average", M2Range: "Above Average", MaxCombo: 4, ComboLife: 1.3,
      M1ComboCooldowns: [0, 0, 0, 1.3], M1ComboLifes: [1.3, 1.3, 1.3, 1.4], M1Speed: 1, M2Speed: 1,
      M1StaminaCost: 32, M2StaminaCost: 42, M2Cooldown: 2.4, M1Endlag: 0.08,
      M2Endlag: 0.4, Endlag: 0.7, StrengthScaling: 0.68, UpperMuscleScaling: 2.4,
      LowerMuscleScaling: 2.4, FatScaling: 0.02, AgilityScaling: 0, AttackSpeedScaling: 0,
      MaxAttackSpeedScale: 0.8, M2MaxAttackSpeedScale: 0.75,
      StaminaScaling: { AttackSpeed: 25, Strength: 30, Muscle: 40, Fat: 40 },
      StaminaScalingCap: { Strength: 60 },
    },
    The_Middle: {
      M1RangeMul: 1, BaseStun: 0.5, BaseDamageM1: 15.9, BaseDamageM2: 17,
      M1Range: "Above Average", M2Range: "Above Average", MaxCombo: 4, ComboLife: 1.3,
      M1ComboCooldowns: [0, 0, 0, 1.3], M1ComboLifes: [1.3, 1.3, 1.3, 1.4], M1Speed: 0.91, M2Speed: 0.91,
      M1StaminaCost: 40, M2StaminaCost: 47, M2Cooldown: 2.4, M1Endlag: 0.1,
      M2Endlag: 0.4, Endlag: 0.7, StrengthScaling: 0.68, UpperMuscleScaling: 2.45,
      LowerMuscleScaling: 2.24, FatScaling: 0.04, AgilityScaling: 0, AttackSpeedScaling: 0,
      MaxAttackSpeedScale: 0.8, M2MaxAttackSpeedScale: 0.75,
      StaminaScaling: { AttackSpeed: 25, Strength: 30, Muscle: 40, Fat: 40 },
      StaminaScalingCap: { Strength: 60 },
    },
    Kure: {
      M1RangeMul: 0.98, BaseStun: 0.5, BaseDamageM1: 14.5, BaseDamageM2: 20.16,
      M1Range: "Average", M2Range: "Above Average", MaxCombo: 4, ComboLife: 1.3,
      M1ComboCooldowns: [0, 0, 0, 1.3], M1ComboLifes: [1.3, 1.3, 1.3, 1.4], M1Speed: 1.21, M2Speed: 0.95,
      M1StaminaCost: 34, M2StaminaCost: 42, M2Cooldown: 2.4, M1Endlag: 0.1,
      M2Endlag: 0.4, Endlag: 0.6, StrengthScaling: 0.75, UpperMuscleScaling: 2.3,
      LowerMuscleScaling: 2.3, FatScaling: 0.03, AgilityScaling: 0, AttackSpeedScaling: 0.1,
      MaxAttackSpeedScale: 0.8, M2MaxAttackSpeedScale: 0.75,
      StaminaScaling: { AttackSpeed: 25, Strength: 30, Muscle: 40, Fat: 40 },
      StaminaScalingCap: { Strength: 60 },
    },
    Raishin: {
      M1RangeMul: 1.03, BaseStun: 0.425, BaseDamageM1: 14, BaseDamageM2: 18,
      M1Range: "High", M2Range: "Above Average", MaxCombo: 4, ComboLife: 1.3,
      M1ComboCooldowns: [0, 0, 0, 1.3], M1ComboLifes: [1.3, 1.3, 1.3, 1.4], M1Speed: 1.5, M2Speed: 1.2,
      M1StaminaCost: 37, M2StaminaCost: 46, M2Cooldown: 2.4, M1Endlag: 0.1,
      M2Endlag: 0.4, Endlag: 0.7, StrengthScaling: 0.7, UpperMuscleScaling: 1.2,
      LowerMuscleScaling: 1.3, FatScaling: 0, AgilityScaling: 0.15, AttackSpeedScaling: 0.3,
      MaxAttackSpeedScale: 0.8, M2MaxAttackSpeedScale: 0.8,
      StaminaScaling: { AttackSpeed: 25, Strength: 30, Muscle: 40, Fat: 40 },
      StaminaScalingCap: { Strength: 60 },
    },
    Sumo: {
      M1RangeMul: 1.02, BaseStun: 0.7, BaseDamageM1: 22.5, BaseDamageM2: 23.5,
      M1Range: "Average", M2Range: "Above Average", MaxCombo: 4, ComboLife: 1.3,
      M1ComboCooldowns: [0, 0, 0, 1.3], M1ComboLifes: [1.3, 1.3, 1.3, 1.4], M1Speed: 0.7, M2Speed: 1,
      M1StaminaCost: 35, M2StaminaCost: 45, M2Cooldown: 2.4, M1Endlag: 0.1,
      M2Endlag: 0.4, Endlag: 0.7, StrengthScaling: 0.15, UpperMuscleScaling: 0.5,
      LowerMuscleScaling: 0.5, FatScaling: 3.6, AgilityScaling: 0, AttackSpeedScaling: 0,
      MaxAttackSpeedScale: 0.8, M2MaxAttackSpeedScale: 0.75,
      StaminaScaling: { AttackSpeed: 25, Strength: 30, Muscle: 40, Fat: 40 },
      StaminaScalingCap: { Strength: 60 },
    },
    Taekwondo: {
      M1RangeMul: 1.05, BaseStun: 0.525, BaseDamageM1: 13.5, BaseDamageM2: 15,
      M1Range: "High", M2Range: "Above Average", MaxCombo: 4, ComboLife: 1.15,
      M1ComboCooldowns: [0.32, 0.38, 0.44, 1.55], M1ComboLifes: [1.3, 1.3, 1.3, 1.4], M1Speed: 1.1, M2Speed: 1,
      M1StaminaCost: 34, M2StaminaCost: 44, M2Cooldown: 2.4, M1Endlag: 0.12,
      M2Endlag: 0.4, Endlag: 0.7, StrengthScaling: 0.7, UpperMuscleScaling: 1.5,
      LowerMuscleScaling: 2.4, FatScaling: 0.02, AgilityScaling: 0, AttackSpeedScaling: 0,
      MaxAttackSpeedScale: 0.8, M2MaxAttackSpeedScale: 0.75,
      StaminaScaling: { AttackSpeed: 25, Strength: 30, Muscle: 40, Fat: 40 },
      StaminaScalingCap: { Strength: 60 },
    },
    Kickboxing: {
      M1RangeMul: 1.05, BaseStun: 0.45, BaseDamageM1: 15.2, BaseDamageM2: 17.55,
      M1Range: "High", M2Range: "Above Average", MaxCombo: 4, ComboLife: 1.3,
      M1ComboCooldowns: [0, 0, 0, 1.3], M1ComboLifes: [1.3, 1.3, 1.3, 1.4], M1Speed: 1.5515, M2Speed: 1.177,
      M1StaminaCost: 34, M2StaminaCost: 44, M2Cooldown: 2.4, M1Endlag: 0.1,
      M2Endlag: 0.4, Endlag: 0.7, StrengthScaling: 0.65, UpperMuscleScaling: 1.7,
      LowerMuscleScaling: 1.5, FatScaling: 0.02, AgilityScaling: 0, AttackSpeedScaling: 0.2,
      MaxAttackSpeedScale: 0.8, M2MaxAttackSpeedScale: 0.8,
      StaminaScaling: { AttackSpeed: 25, Strength: 30, Muscle: 40, Fat: 40 },
      StaminaScalingCap: { Strength: 60 },
    },
    Sky: {
      M1RangeMul: 1, BaseStun: 0.4, BaseDamageM1: 18, BaseDamageM2: 22,
      M1Range: "High", M2Range: "Above Average", MaxCombo: 4, ComboLife: 1.3,
      M1ComboCooldowns: [0, 0, 0, 1.3], M1ComboLifes: [1.3, 1.3, 1.3, 1.4], M1Speed: 0.95, M2Speed: 1,
      M1StaminaCost: 30, M2StaminaCost: 40, M2Cooldown: 2.4, M1Endlag: 0.12,
      M2Endlag: 0.4, Endlag: 0.6, StrengthScaling: 0.65, UpperMuscleScaling: 2.7,
      LowerMuscleScaling: 2.7, FatScaling: 0.1, AgilityScaling: 0, AttackSpeedScaling: 0,
      MaxAttackSpeedScale: 0.9, M2MaxAttackSpeedScale: 0.75,
      StaminaScaling: { AttackSpeed: 25, Strength: 30, Muscle: 40, Fat: 40 },
      StaminaScalingCap: { Strength: 60 },
    },
    Zhin: {
      M1RangeMul: 1, BaseStun: 0.425, BaseDamageM1: 18, BaseDamageM2: 22,
      M1Range: "High", M2Range: "Above Average", MaxCombo: 4, ComboLife: 1.3,
      M1ComboCooldowns: [0, 0, 0, 1.3], M1ComboLifes: [1.3, 1.3, 1.3, 1.4], M1Speed: 0.95, M2Speed: 0.9,
      M1StaminaCost: 30, M2StaminaCost: 40, M2Cooldown: 2.4, M1Endlag: 0.12,
      M2Endlag: 0.4, Endlag: 0.6, StrengthScaling: 0.65, UpperMuscleScaling: 2.1,
      LowerMuscleScaling: 3, FatScaling: 0.1, AgilityScaling: 0, AttackSpeedScaling: 0,
      MaxAttackSpeedScale: 0.9, M2MaxAttackSpeedScale: 0.75,
      StaminaScaling: { AttackSpeed: 25, Strength: 30, Muscle: 40, Fat: 40 },
      StaminaScalingCap: { Strength: 60 },
    },
    Cat: {
      M1RangeMul: 1, BaseStun: 0.5, BaseDamageM1: 18, BaseDamageM2: 22,
      M1Range: "High", M2Range: "Above Average", MaxCombo: 4, ComboLife: 1.3,
      M1ComboCooldowns: [0, 0, 0, 1.3], M1ComboLifes: [1.3, 1.3, 1.3, 1.4], M1Speed: 0.95, M2Speed: 1,
      M1StaminaCost: 30, M2StaminaCost: 40, M2Cooldown: 2.4, M1Endlag: 0.12,
      M2Endlag: 0.4, Endlag: 0.5, StrengthScaling: 0.65, UpperMuscleScaling: 2.5,
      LowerMuscleScaling: 2.7, FatScaling: 0.1, AgilityScaling: 0, AttackSpeedScaling: 0,
      MaxAttackSpeedScale: 0.9, M2MaxAttackSpeedScale: 0.75,
      StaminaScaling: { AttackSpeed: 25, Strength: 30, Muscle: 40, Fat: 40 },
      StaminaScalingCap: { Strength: 60 },
    },
    Kujin: {
      M1RangeMul: 1, BaseStun: 0.7, BaseDamageM1: 18, BaseDamageM2: 22,
      M1Range: "High", M2Range: "Above Average", MaxCombo: 4, ComboLife: 1.3,
      M1ComboCooldowns: [0, 0, 0, 1.3], M1ComboLifes: [1.3, 1.3, 1.3, 1.4], M1Speed: 0.95, M2Speed: 1,
      M1StaminaCost: 30, M2StaminaCost: 40, M2Cooldown: 2.4, M1Endlag: 0.12,
      M2Endlag: 0.4, Endlag: 0.5, StrengthScaling: 0.65, UpperMuscleScaling: 2.7,
      LowerMuscleScaling: 2.7, FatScaling: 0.04, AgilityScaling: 0, AttackSpeedScaling: 0,
      MaxAttackSpeedScale: 0.8, M2MaxAttackSpeedScale: 0.75,
      StaminaScaling: { AttackSpeed: 25, Strength: 30, Muscle: 40, Fat: 40 },
      StaminaScalingCap: { Strength: 60 },
    },
    Kazu: {
      M1RangeMul: 1, BaseStun: 0.7, BaseDamageM1: 18, BaseDamageM2: 22,
      M1Range: "High", M2Range: "Above Average", MaxCombo: 4, ComboLife: 1.3,
      M1ComboCooldowns: [0, 0, 0, 1.3], M1ComboLifes: [1.3, 1.3, 1.3, 1.4], M1Speed: 0.95, M2Speed: 1,
      M1StaminaCost: 30, M2StaminaCost: 40, M2Cooldown: 2.4, M1Endlag: 0.12,
      M2Endlag: 0.4, Endlag: 0.6, StrengthScaling: 0.65, UpperMuscleScaling: 2.7,
      LowerMuscleScaling: 2.7, FatScaling: 0.1, AgilityScaling: 0, AttackSpeedScaling: 0,
      MaxAttackSpeedScale: 0.9, M2MaxAttackSpeedScale: 0.75,
      StaminaScaling: { AttackSpeed: 25, Strength: 30, Muscle: 40, Fat: 40 },
      StaminaScalingCap: { Strength: 60 },
    },
    WarAxe: {
      M1RangeMul: 1, BaseStun: 0.7, BaseDamageM1: 16.5, BaseDamageM2: 19,
      M1Range: "High", M2Range: "Above Average", MaxCombo: 4, ComboLife: 1.3,
      M1ComboCooldowns: [0, 0, 0, 1.3], M1ComboLifes: [1.3, 1.3, 1.3, 1.4], M1Speed: 0.95, M2Speed: 1,
      M1StaminaCost: 30, M2StaminaCost: 40, M2Cooldown: 2.4, M1Endlag: 0.12,
      M2Endlag: 0.4, Endlag: 0.6, StrengthScaling: 0.75, UpperMuscleScaling: 2.1,
      LowerMuscleScaling: 3, FatScaling: 0.1, AgilityScaling: 0, AttackSpeedScaling: 0,
      MaxAttackSpeedScale: 0.9, M2MaxAttackSpeedScale: 0.75,
      StaminaScaling: { AttackSpeed: 25, Strength: 30, Muscle: 40, Fat: 40 },
      StaminaScalingCap: { Strength: 60 },
    },
    "Grand-WarAxe": {
      M1RangeMul: 1.12, BaseStun: 0.75, BaseDamageM1: 24.5, BaseDamageM2: 25.5,
      M1Range: "Average", M2Range: "Above Average", MaxCombo: 4, ComboLife: 1.3,
      M1ComboCooldowns: [0, 0, 0, 1.3], M1ComboLifes: [1.3, 1.3, 1.3, 1.4], M1Speed: 2, M2Speed: 2.3,
      M1StaminaCost: 30, M2StaminaCost: 45, M2Cooldown: 2.4, M1Endlag: 0.1,
      M2Endlag: 0.4, Endlag: 0.7, StrengthScaling: 0.18, UpperMuscleScaling: 2.1,
      LowerMuscleScaling: 2.1, FatScaling: 0.9, AgilityScaling: 0, AttackSpeedScaling: 0,
      MaxAttackSpeedScale: 0.8, M2MaxAttackSpeedScale: 0.75,
      StaminaScaling: { AttackSpeed: 25, Strength: 30, Muscle: 40, Fat: 40 },
      StaminaScalingCap: { Strength: 60 },
    },
    BoxingLongGuard: {
      M1RangeMul: 1, BaseStun: 0.425, BaseDamageM1: 13, BaseDamageM2: 15,
      M1Range: "High", M2Range: "Above Average", MaxCombo: 4, ComboLife: 1.3,
      M1ComboCooldowns: [0, 0, 0, 1.3], M1ComboLifes: [1.3, 1.3, 1.3, 1.4], M1Speed: 1.45, M2Speed: 1.1,
      M1StaminaCost: 27, M2StaminaCost: 37, M2Cooldown: 2.4, M1Endlag: 0.1,
      M2Endlag: 0.4, Endlag: 0.7, StrengthScaling: 0.75, UpperMuscleScaling: 1.7,
      LowerMuscleScaling: 1.5, FatScaling: 0.005, AgilityScaling: 0, AttackSpeedScaling: 0.2,
      MaxAttackSpeedScale: 0.8, M2MaxAttackSpeedScale: 0.8,
      StaminaScaling: { AttackSpeed: 25, Strength: 30, Muscle: 40, Fat: 40 },
      StaminaScalingCap: { Strength: 60 },
    },
    Muay_Thai: {
      M1RangeMul: 1.03, BaseStun: 0.5, BaseDamageM1: 13.6, BaseDamageM2: 14.6,
      M1Range: "High", M2Range: "Above Average", MaxCombo: 4, ComboLife: 1.3,
      M1ComboCooldowns: [0, 0, 0, 1.3], M1ComboLifes: [1.3, 1.3, 1.3, 1.4], M1Speed: 0.9, M2Speed: 1,
      M1StaminaCost: 33, M2StaminaCost: 42, M2Cooldown: 2.4, M1Endlag: 0.1,
      M2Endlag: 0.4, Endlag: 0.7, StrengthScaling: 0.75, UpperMuscleScaling: 2.35,
      LowerMuscleScaling: 2.8, FatScaling: 0, AgilityScaling: 0, AttackSpeedScaling: 0.1,
      MaxAttackSpeedScale: 0.8, M2MaxAttackSpeedScale: 0.75,
      StaminaScaling: { AttackSpeed: 25, Strength: 30, Muscle: 40, Fat: 40 },
      StaminaScalingCap: { Strength: 60 },
    },
    Wrestling: {
      M1RangeMul: 0.97, BaseStun: 0.73, BaseDamageM1: 18.55, BaseDamageM2: 19.27,
      M1Range: "Average", M2Range: "Above Average", MaxCombo: 4, ComboLife: 1.3,
      M1ComboCooldowns: [0, 0, 0, 1.3], M1ComboLifes: [1.3, 1.3, 1.3, 1.4], M1Speed: 0.8, M2Speed: 0.8,
      M1StaminaCost: 34, M2StaminaCost: 44, M2Cooldown: 2.4, M1Endlag: 0.1,
      M2Endlag: 0.4, Endlag: 0.7, StrengthScaling: 0.18, UpperMuscleScaling: 2.3,
      LowerMuscleScaling: 2.3, FatScaling: 0.04, AgilityScaling: 0, AttackSpeedScaling: 0,
      MaxAttackSpeedScale: 0.8, M2MaxAttackSpeedScale: 0.75, TMThreshold: 1000,
      StaminaScaling: { AttackSpeed: 25, Strength: 30, Muscle: 40, Fat: 40 },
      StaminaScalingCap: { Strength: 60 },
    },
    Karate: {
      M1RangeMul: 1.02, BaseStun: 0.475, BaseDamageM1: 13, BaseDamageM2: 14,
      M1Range: "High", M2Range: "Above Average", MaxCombo: 4, ComboLife: 1.3,
      M1ComboCooldowns: [0, 0, 0, 1.3], M1ComboLifes: [1.3, 1.3, 1.3, 1.4], M1Speed: 1, M2Speed: 1,
      M1StaminaCost: 33.5, M2StaminaCost: 42.5, M2Cooldown: 2.4, M1Endlag: 0.1,
      M2Endlag: 0.4, Endlag: 0.7, StrengthScaling: 0.8, UpperMuscleScaling: 2.2,
      LowerMuscleScaling: 2.2, FatScaling: 0.02, AgilityScaling: 0, AttackSpeedScaling: 0.1,
      MaxAttackSpeedScale: 0.8, M2MaxAttackSpeedScale: 0.9,
      StaminaScaling: { AttackSpeed: 25, Strength: 30, Muscle: 40, Fat: 40 },
      StaminaScalingCap: { Strength: 60 },
    },
    Niko: {
      M1RangeMul: 1, BaseStun: 0.5, BaseDamageM1: 14.75, BaseDamageM2: 20.06,
      M1Range: "High", M2Range: "Above Average", MaxCombo: 4, ComboLife: 1.3,
      M1ComboCooldowns: [0, 0, 0, 1.3], M1ComboLifes: [1.3, 1.3, 1.3, 1.4], M1Speed: 1.32, M2Speed: 1.3,
      M1StaminaCost: 37, M2StaminaCost: 42.5, M2Cooldown: 2.4, M1Endlag: 0.1,
      M2Endlag: 0.4, Endlag: 0.7, StrengthScaling: 0.78, UpperMuscleScaling: 2.4,
      LowerMuscleScaling: 2.3, FatScaling: 0.04, AgilityScaling: 0, AttackSpeedScaling: 0.1,
      MaxAttackSpeedScale: 0.8, M2MaxAttackSpeedScale: 0.9,
      StaminaScaling: { AttackSpeed: 25, Strength: 30, Muscle: 40, Fat: 40 },
      StaminaScalingCap: { Strength: 60 },
    },
    Reinhold: {
      M1RangeMul: 1, BaseStun: 0.7, BaseDamageM1: 18.8, BaseDamageM2: 19.6,
      M1Range: "Average", M2Range: "Above Average", MaxCombo: 4, ComboLife: 1.3,
      M1ComboCooldowns: [0, 0, 0, 1.3], M1ComboLifes: [1.3, 1.3, 1.3, 1.4], M1Speed: 0.8, M2Speed: 0.8,
      M1StaminaCost: 35, M2StaminaCost: 40, M2Cooldown: 2.4, M1Endlag: 0.1,
      M2Endlag: 0.4, Endlag: 0.7, StrengthScaling: 0.2, UpperMuscleScaling: 2.4,
      LowerMuscleScaling: 2.4, FatScaling: 0.01, AgilityScaling: 0, AttackSpeedScaling: 0,
      MaxAttackSpeedScale: 0.8, M2MaxAttackSpeedScale: 0.75, TMThreshold: 1000,
      StaminaScaling: { AttackSpeed: 25, Strength: 30, Muscle: 40, Fat: 40 },
      StaminaScalingCap: { Strength: 60 },
    },
    Demon_Fist: {
      M1RangeMul: 1, BaseStun: 0.7, BaseDamageM1: 16, BaseDamageM2: 15.5,
      M1Range: "High", M2Range: "Above Average", MaxCombo: 4, ComboLife: 1.3,
      M1ComboCooldowns: [0, 0, 0, 1.3], M1ComboLifes: [1.3, 1.3, 1.3, 1.4], M1Speed: 1.65, M2Speed: 1,
      M1StaminaCost: 35, M2StaminaCost: 44, M2Cooldown: 2.4, M1Endlag: 0.1,
      M2Endlag: 0.4, Endlag: 0.7, StrengthScaling: 0.6, UpperMuscleScaling: 2.6,
      LowerMuscleScaling: 2.35, FatScaling: 0.01, AgilityScaling: 0, AttackSpeedScaling: 0.1,
      MaxAttackSpeedScale: 0.8, M2MaxAttackSpeedScale: 0.9,
      StaminaScaling: { AttackSpeed: 25, Strength: 30, Muscle: 40, Fat: 40 },
      StaminaScalingCap: { Strength: 60 },
    },
    Ya: {
      M1RangeMul: 1, BaseStun: 0.73, BaseDamageM1: 17.75, BaseDamageM2: 18.5,
      M1Range: "High", M2Range: "High", MaxCombo: 4, ComboLife: 1.3,
      M1ComboCooldowns: [0, 0, 0, 1.3], M1ComboLifes: [1.3, 1.3, 1.3, 1.4], M1Speed: 0.9, M2Speed: 1.1,
      M1StaminaCost: 30, M2StaminaCost: 40, M2Cooldown: 2.4, M1Endlag: 0.06,
      M2Endlag: 0.4, Endlag: 0.7, StrengthScaling: 0.675, UpperMuscleScaling: 2.7,
      LowerMuscleScaling: 2.7, FatScaling: 0.1, AgilityScaling: 0, AttackSpeedScaling: 0.2,
      MaxAttackSpeedScale: 1, M2MaxAttackSpeedScale: 0.8,
      StaminaScaling: { AttackSpeed: 25, Strength: 30, Muscle: 40, Fat: 40 },
      StaminaScalingCap: { Strength: 60 },
    },
    "Yuzuki-no-Mai": {
      M1RangeMul: 1, BaseStun: 0.73, BaseDamageM1: 17.75, BaseDamageM2: 18.5,
      M1Range: "High", M2Range: "High", MaxCombo: 4, ComboLife: 1.3,
      M1ComboCooldowns: [0, 0, 0, 1.3], M1ComboLifes: [1.3, 1.3, 1.3, 1.4], M1Speed: 0.9, M2Speed: 1.1,
      M1StaminaCost: 30, M2StaminaCost: 40, M2Cooldown: 2.4, M1Endlag: 0.06,
      M2Endlag: 0.4, Endlag: 0.7, StrengthScaling: 0.675, UpperMuscleScaling: 2.7,
      LowerMuscleScaling: 2.7, FatScaling: 0.1, AgilityScaling: 0, AttackSpeedScaling: 0.2,
      MaxAttackSpeedScale: 1, M2MaxAttackSpeedScale: 0.8,
      StaminaScaling: { AttackSpeed: 25, Strength: 30, Muscle: 40, Fat: 40 },
      StaminaScalingCap: { Strength: 60 },
    },
  },
  // -- CombatCalcsData.SkillScaling --
  skillScaling: {
    Steel_Blast: { StrengthScaling: 1.6, UpperMuscleScaling: 2.7, LowerMuscleScaling: 2.7, FatScaling: 0, AgilityScaling: 0.3, AttackSpeedScaling: 0.4 },
    Flash_Fire: { StrengthScaling: 1.4, UpperMuscleScaling: 1.5, LowerMuscleScaling: 2, FatScaling: 0, AgilityScaling: 0.3, AttackSpeedScaling: 0.4 },
    ChokeSlam: { StrengthScaling: 0.188, UpperMuscleScaling: 2, LowerMuscleScaling: 1.758, FatScaling: 0, AgilityScaling: 0, AttackSpeedScaling: 0.188 },
    Nerve_Strike: { StrengthScaling: 2, UpperMuscleScaling: 0, LowerMuscleScaling: 0, FatScaling: 0, AgilityScaling: 0.5, AttackSpeedScaling: 1 },
    Lightning_Flash: { StrengthScaling: 1.8, UpperMuscleScaling: 0, LowerMuscleScaling: 0, FatScaling: 0, AgilityScaling: 0.43, AttackSpeedScaling: 0.25 },
    Rising_Heel: { StrengthScaling: 1.6, UpperMuscleScaling: 0, LowerMuscleScaling: 1.2, FatScaling: 0, AgilityScaling: 1, AttackSpeedScaling: 0.5 },
    Anaconda_Choke: { StrengthScaling: 1, UpperMuscleScaling: 1.87, LowerMuscleScaling: 1.9, FatScaling: 0, AgilityScaling: 1, AttackSpeedScaling: 0.5 },
    Hardpoint: { StrengthScaling: 2.3, UpperMuscleScaling: 0.5, LowerMuscleScaling: 0, FatScaling: 0, AgilityScaling: 1, AttackSpeedScaling: 0.4 },
    WhirlwindSpin: { StrengthScaling: 2, UpperMuscleScaling: 0, LowerMuscleScaling: 0, FatScaling: 0, AgilityScaling: 1, AttackSpeedScaling: 0.5 },
    Elbow_Cut: { StrengthScaling: 2, UpperMuscleScaling: 0.5, LowerMuscleScaling: 0.5, FatScaling: 0, AgilityScaling: 0.3, AttackSpeedScaling: 0.1 },
    Brute_Throw: { StrengthScaling: 0.5, UpperMuscleScaling: 2.45, LowerMuscleScaling: 2.45, FatScaling: 0, AgilityScaling: 0, AttackSpeedScaling: 0.1 },
    Mountain_Breaker: { StrengthScaling: 0.6, UpperMuscleScaling: 0.6, LowerMuscleScaling: 0.6, FatScaling: 0, AgilityScaling: 0.3, AttackSpeedScaling: 0.1 },
    A_Just_Vengeance: { StrengthScaling: 1.2, UpperMuscleScaling: 2.21, LowerMuscleScaling: 2, FatScaling: 0, AgilityScaling: 0.5, AttackSpeedScaling: 0.5 },
    Right_Koken: { StrengthScaling: 1.5, UpperMuscleScaling: 0.5, LowerMuscleScaling: 0, FatScaling: 0, AgilityScaling: 1, AttackSpeedScaling: 1 },
    Knee_Strike: { StrengthScaling: 2.85, UpperMuscleScaling: 0, LowerMuscleScaling: 0.75, FatScaling: 0, AgilityScaling: 0.5, AttackSpeedScaling: 0.5 },
    Body_Sweep: { StrengthScaling: 1.9, UpperMuscleScaling: 1.5, LowerMuscleScaling: 2.3, FatScaling: 0, AgilityScaling: 1, AttackSpeedScaling: 0.5 },
    Gazelle_Punch: { StrengthScaling: 1.905, UpperMuscleScaling: 0.635, LowerMuscleScaling: 0, FatScaling: 0, AgilityScaling: 1.27, AttackSpeedScaling: 1.27 },
    Iron_Breaker: { StrengthScaling: 2.5, UpperMuscleScaling: 2.5, LowerMuscleScaling: 1.5, FatScaling: 0, AgilityScaling: 0.3, AttackSpeedScaling: 0.4 },
    Head_Slam: { StrengthScaling: 2, UpperMuscleScaling: 0, LowerMuscleScaling: 0, FatScaling: 0, AgilityScaling: 1, AttackSpeedScaling: 0.5 },
    Binding_Hold: { StrengthScaling: 2.5, UpperMuscleScaling: 0, LowerMuscleScaling: 0, FatScaling: 0, AgilityScaling: 1, AttackSpeedScaling: 1 },
    Flying_Knee: { StrengthScaling: 2.6, UpperMuscleScaling: 0, LowerMuscleScaling: 0.5, FatScaling: 0, AgilityScaling: 0.5, AttackSpeedScaling: 0.25 },
    Cranium_Break: { StrengthScaling: 0.6, UpperMuscleScaling: 2.6, LowerMuscleScaling: 0.5, FatScaling: 0, AgilityScaling: 0.1, AttackSpeedScaling: 0.2 },
    Bulldoze: { StrengthScaling: 0.05, UpperMuscleScaling: 0.4, LowerMuscleScaling: 0.4, FatScaling: 3.2, AgilityScaling: 0.1, AttackSpeedScaling: 0.5 },
    Body_Drop: { StrengthScaling: 0.03, UpperMuscleScaling: 0.5, LowerMuscleScaling: 0.5, FatScaling: 3.3, AgilityScaling: 0.1, AttackSpeedScaling: 0.5 },
    Hammer_Palm: { StrengthScaling: 0.5, UpperMuscleScaling: 2.1, LowerMuscleScaling: 2.1, FatScaling: 0, AgilityScaling: 0, AttackSpeedScaling: 0.5 },
    Flicker_Jab: { StrengthScaling: 1.397, UpperMuscleScaling: 0, LowerMuscleScaling: 0, FatScaling: 0, AgilityScaling: 0.635, AttackSpeedScaling: 1.27 },
    Suplex: { StrengthScaling: 0.188, UpperMuscleScaling: 2.5, LowerMuscleScaling: 1.7, FatScaling: 0, AgilityScaling: 0.038, AttackSpeedScaling: 0.188 },
    Blazing_Dragon: { StrengthScaling: 0.8, UpperMuscleScaling: 1.5, LowerMuscleScaling: 1.5, FatScaling: 0, AgilityScaling: 0.3, AttackSpeedScaling: 0.4 },
    Dream_Walking: { StrengthScaling: 2, UpperMuscleScaling: 0, LowerMuscleScaling: 0, FatScaling: 0, AgilityScaling: 0.8, AttackSpeedScaling: 0.2 },
    Write_em_all_down: { StrengthScaling: 1, UpperMuscleScaling: 2.7, LowerMuscleScaling: 0.95, FatScaling: 0, AgilityScaling: 0.5, AttackSpeedScaling: 0.5 },
    Devil_Lance: { StrengthScaling: 1.5, UpperMuscleScaling: 0.5, LowerMuscleScaling: 0, FatScaling: 0, AgilityScaling: 1, AttackSpeedScaling: 1 },
    Palm_Bomb: { StrengthScaling: 1.7, UpperMuscleScaling: 1, LowerMuscleScaling: 1, FatScaling: 0, AgilityScaling: 0.5, AttackSpeedScaling: 0.4 },
    Feinting_Elbow: { StrengthScaling: 1.25, UpperMuscleScaling: 1, LowerMuscleScaling: 0, FatScaling: 0, AgilityScaling: 1, AttackSpeedScaling: 1 },
    Liver_Blow: { StrengthScaling: 1.651, UpperMuscleScaling: 0.635, LowerMuscleScaling: 0, FatScaling: 0, AgilityScaling: 0.635, AttackSpeedScaling: 1.27 },
    Earth_Shatter: { StrengthScaling: 2.2, UpperMuscleScaling: 4.45, LowerMuscleScaling: 2, FatScaling: 0, AgilityScaling: 0.1, AttackSpeedScaling: 0.2 },
    Neck_Breaker: { StrengthScaling: 2.85, UpperMuscleScaling: 1.5, LowerMuscleScaling: 0.5, FatScaling: 0, AgilityScaling: 0.3, AttackSpeedScaling: 0.4 },
    Bear_Hug: { StrengthScaling: 0.3, UpperMuscleScaling: 2.1, LowerMuscleScaling: 2.1, FatScaling: 0, AgilityScaling: 0.5, AttackSpeedScaling: 0 },
    Roundhouse_Kick: { StrengthScaling: 1.7, UpperMuscleScaling: 0, LowerMuscleScaling: 0.5, FatScaling: 0, AgilityScaling: 0.5, AttackSpeedScaling: 0.5 },
    Scissor_Sweep: { StrengthScaling: 1.26, UpperMuscleScaling: 2, LowerMuscleScaling: 2.6, FatScaling: 0, AgilityScaling: 1, AttackSpeedScaling: 0.5 },
    Lion_Bite: { StrengthScaling: 2, UpperMuscleScaling: 0.6, LowerMuscleScaling: 0.6, FatScaling: 0, AgilityScaling: 0.3, AttackSpeedScaling: 0.1 },
    Flying_Side_Kick: { StrengthScaling: 1.4, UpperMuscleScaling: 0, LowerMuscleScaling: 1, FatScaling: 0, AgilityScaling: 1, AttackSpeedScaling: 0.5 },
    Counter_Cut: { StrengthScaling: 1.905, UpperMuscleScaling: 0.8, LowerMuscleScaling: 0, FatScaling: 0, AgilityScaling: 1.27, AttackSpeedScaling: 1.27 },
    Pure_Taekwondo: { StrengthScaling: 1, UpperMuscleScaling: 0, LowerMuscleScaling: 0.9, FatScaling: 0, AgilityScaling: 0, AttackSpeedScaling: 0.1 },
    Six_Seiken: { StrengthScaling: 1.7, UpperMuscleScaling: 1, LowerMuscleScaling: 0, FatScaling: 0, AgilityScaling: 1.5, AttackSpeedScaling: 1 },
    Russian_Tie: { StrengthScaling: 1.4, UpperMuscleScaling: 2.5, LowerMuscleScaling: 2, FatScaling: 0, AgilityScaling: 1, AttackSpeedScaling: 0.5 },
    Thunderclap: { StrengthScaling: 2.3, UpperMuscleScaling: 1, LowerMuscleScaling: 0, FatScaling: 0, AgilityScaling: 0.6, AttackSpeedScaling: 0.8 },
    StarDrop: { StrengthScaling: 2.5, UpperMuscleScaling: 0, LowerMuscleScaling: 0, FatScaling: 0, AgilityScaling: 1.2, AttackSpeedScaling: 0.4 },
    Spinning_Backfist: { StrengthScaling: 1.3, UpperMuscleScaling: 0.5, LowerMuscleScaling: 0, FatScaling: 0, AgilityScaling: 0.8, AttackSpeedScaling: 0.5 },
    Swift_Kick: { StrengthScaling: 1.3, UpperMuscleScaling: 0, LowerMuscleScaling: 0.4, FatScaling: 0, AgilityScaling: 0.8, AttackSpeedScaling: 0.5 },
    Oblique_Kick: { StrengthScaling: 1.2, UpperMuscleScaling: 0, LowerMuscleScaling: 0.4, FatScaling: 0, AgilityScaling: 0.8, AttackSpeedScaling: 0.5 },
    Flashing_Steel: { StrengthScaling: 1.6, UpperMuscleScaling: 2.5, LowerMuscleScaling: 1.5, FatScaling: 0, AgilityScaling: 0.3, AttackSpeedScaling: 0.4 },
    Ear_Clap: { StrengthScaling: 1.3, UpperMuscleScaling: 3.56, LowerMuscleScaling: 0.089, FatScaling: 0, AgilityScaling: 0.2, AttackSpeedScaling: 0.5 },
    Elbow_Smash: { StrengthScaling: 1.17, UpperMuscleScaling: 1.5, LowerMuscleScaling: 0.5, FatScaling: 0, AgilityScaling: 1, AttackSpeedScaling: 1 },
    Rock_Punch: { StrengthScaling: 0.5, UpperMuscleScaling: 2.1, LowerMuscleScaling: 2.1, FatScaling: 0, AgilityScaling: 0, AttackSpeedScaling: 0.1 },
    Garuda_Fang: { StrengthScaling: 2.5, UpperMuscleScaling: 0, LowerMuscleScaling: 0.5, FatScaling: 0, AgilityScaling: 0.5, AttackSpeedScaling: 0.5 },
    Tatsumaki: { StrengthScaling: 2.3, UpperMuscleScaling: 0.5, LowerMuscleScaling: 2, FatScaling: 0, AgilityScaling: 0.3, AttackSpeedScaling: 0.4 },
    Ravage: { StrengthScaling: 1.5, UpperMuscleScaling: 2.5, LowerMuscleScaling: 2, FatScaling: 0, AgilityScaling: 1, AttackSpeedScaling: 1 },
    Hyakuretsukyaku: { StrengthScaling: 1.54, UpperMuscleScaling: 1.2, LowerMuscleScaling: 2, FatScaling: 0, AgilityScaling: 0.3, AttackSpeedScaling: 0.4 },
    Hadouken: { StrengthScaling: 1.2, UpperMuscleScaling: 2, LowerMuscleScaling: 1.5, FatScaling: 0, AgilityScaling: 0.3, AttackSpeedScaling: 0.4 },
    Shoryuken: { StrengthScaling: 1.4, UpperMuscleScaling: 1.5, LowerMuscleScaling: 1.8, FatScaling: 0, AgilityScaling: 0.3, AttackSpeedScaling: 0.4 },
    Jellyfish_Hold: { StrengthScaling: 2.9, UpperMuscleScaling: 1.3, LowerMuscleScaling: 0.5, FatScaling: 0, AgilityScaling: 0.3, AttackSpeedScaling: 0.4 },
    Weeping_Willow: { StrengthScaling: 2.5, UpperMuscleScaling: 0, LowerMuscleScaling: 0, FatScaling: 0, AgilityScaling: 0.3, AttackSpeedScaling: 0.4 },
    Sit_Through: { StrengthScaling: 1.37, UpperMuscleScaling: 2.4, LowerMuscleScaling: 2.4, FatScaling: 0, AgilityScaling: 1, AttackSpeedScaling: 0.5 },
    Palm_Barrage: { StrengthScaling: 0.5, UpperMuscleScaling: 0.4, LowerMuscleScaling: 0, FatScaling: 3.2, AgilityScaling: 0.1, AttackSpeedScaling: 0.5 },
    Cascade: { StrengthScaling: 0.5, UpperMuscleScaling: 1.2, LowerMuscleScaling: 1.2, FatScaling: 0, AgilityScaling: 0.3, AttackSpeedScaling: 0.2 },
    Predictive_Strikes: { StrengthScaling: 0.85, UpperMuscleScaling: 0.5, LowerMuscleScaling: 3, FatScaling: 0, AgilityScaling: 0.3, AttackSpeedScaling: 0.3 },
    Kicking: { StrengthScaling: 0.9, UpperMuscleScaling: 0.95, LowerMuscleScaling: 2.4, FatScaling: 0, AgilityScaling: 0.5, AttackSpeedScaling: 0.25 },
    Cleaving_Fang: { StrengthScaling: 2, UpperMuscleScaling: 0, LowerMuscleScaling: 0.5, FatScaling: 0, AgilityScaling: 0.7, AttackSpeedScaling: 1 },
    Shockwave_Palm: { StrengthScaling: 1.6, UpperMuscleScaling: 2, LowerMuscleScaling: 1.5, FatScaling: 0, AgilityScaling: 1, AttackSpeedScaling: 1 },
    Avidya: { StrengthScaling: 2.2, UpperMuscleScaling: 0.6, LowerMuscleScaling: 0.6, FatScaling: 0, AgilityScaling: 0.3, AttackSpeedScaling: 0.1 },
    Whirl_Slam: { StrengthScaling: 0.188, UpperMuscleScaling: 2, LowerMuscleScaling: 1.85, FatScaling: 0, AgilityScaling: 0.075, AttackSpeedScaling: 0.113 },
    ElbowDrop: { StrengthScaling: 0.225, UpperMuscleScaling: 1.558, LowerMuscleScaling: 1.558, FatScaling: 0, AgilityScaling: 0.375, AttackSpeedScaling: 0 },
    Rushing_Kick: { StrengthScaling: 1.6, UpperMuscleScaling: 0, LowerMuscleScaling: 0.35, FatScaling: 0, AgilityScaling: 1, AttackSpeedScaling: 0.5 },
    Crushing_Throw: { StrengthScaling: 0.05, UpperMuscleScaling: 0.6, LowerMuscleScaling: 0.6, FatScaling: 3.3, AgilityScaling: 0.1, AttackSpeedScaling: 0.5 },
    Raging_Elbow: { StrengthScaling: 2.4, UpperMuscleScaling: 1.3, LowerMuscleScaling: 0, FatScaling: 0, AgilityScaling: 0.5, AttackSpeedScaling: 0.5 },
    Promised_Suffering: { StrengthScaling: 0.8, UpperMuscleScaling: 0.95, LowerMuscleScaling: 2.5, FatScaling: 0, AgilityScaling: 0.5, AttackSpeedScaling: 0.5 },
    Triple_Kick: { StrengthScaling: 2.2, UpperMuscleScaling: 0, LowerMuscleScaling: 0.35, FatScaling: 0, AgilityScaling: 1, AttackSpeedScaling: 0.5 },
    Rolling: { StrengthScaling: 1.4, UpperMuscleScaling: 0, LowerMuscleScaling: 1.2, FatScaling: 0, AgilityScaling: 0.8, AttackSpeedScaling: 0.5 },
    Questionmark_Kick: { StrengthScaling: 1.5, UpperMuscleScaling: 0, LowerMuscleScaling: 0.3, FatScaling: 0, AgilityScaling: 0.8, AttackSpeedScaling: 0.5 },
    Spinning_Elbow: { StrengthScaling: 2.35, UpperMuscleScaling: 0.5, LowerMuscleScaling: 0, FatScaling: 0, AgilityScaling: 0.5, AttackSpeedScaling: 0.25 },
    OneTwo: { StrengthScaling: 1.27, UpperMuscleScaling: 1.143, LowerMuscleScaling: 0, FatScaling: 0, AgilityScaling: 0, AttackSpeedScaling: 0.127 },
    Double_Kick: { StrengthScaling: 1.55, UpperMuscleScaling: 0, LowerMuscleScaling: 0.35, FatScaling: 0, AgilityScaling: 0.7, AttackSpeedScaling: 0.5 },
    Payback: { StrengthScaling: 1.169, UpperMuscleScaling: 2, LowerMuscleScaling: 2, FatScaling: 0, AgilityScaling: 0.5, AttackSpeedScaling: 0.1 },
    // Removed 2026-08-18: `Eblow_Cut` was the typo key, fixed live to Elbow_Cut.
    // `MaDeedKalok` has no live SkillScaling entry, so the game falls back to the
    // 4.5 legacy multiplier; carrying a scaling here made the site under-report it
    // (114.64 vs the live 147.13 at the default build). Restore only if the live
    // module gains a real entry — see PROJECT_STATE.md's open design decision.
  },
  // -- CombatCalcsData.Skills (key -> entry; SkillData.Power is the base for skill damage) --
  skills: {
    Steel_Blast: { DisplayName: "Steel Blast", Style: "Niko", Cooldown: 36, StaminaCost: -1, HyperArmour: true, ClashPriority: 2, IsExtender: false, SkillData: { Cooldown: 30, Power: 12.45, Range: 3, Speed: 1 } },
    Flash_Fire: { DisplayName: "Flash Fire", Style: "Niko", Cooldown: 33, StaminaCost: -1, HyperArmour: true, ClashPriority: 2, SkillData: { Cooldown: 30, Power: 14, Range: 3, Speed: 1 } },
    ChokeSlam: { DisplayName: "Choke Slam", Style: "Wrestling", Cooldown: 55, StaminaCost: -1, HyperArmour: true, GrabSkill: true, IFrame: true, ClashPriority: 1, SkillData: { Cooldown: 60, Power: 20.128, Range: 6, Speed: 1 } },
    Nerve_Strike: { DisplayName: "Nerve Strike", Style: "Aikido", Cooldown: 30, StaminaCost: -1, CounterSkill: true, IFrame: true, ClashPriority: 1, SkillData: { Cooldown: 30, Power: 14.5, Range: 5, Speed: 1 } },
    Lightning_Flash: { DisplayName: "Lightning Flash", Style: "Raishin", Cooldown: 32, StaminaCost: -1, IFrame: true, ClashPriority: 1, IsExtender: true, SkillData: { Cooldown: 35, Power: 11.3, Range: 35, Speed: 1 } },
    Rising_Heel: { DisplayName: "Rising Heel", Style: "Taekwondo", Cooldown: 40, StaminaCost: -1, ClashPriority: 1, SkillData: { Cooldown: 37, Power: 15, Range: 6, Speed: 1 } },
    Anaconda_Choke: { DisplayName: "Anaconda Choke", Style: "Jujutsu", Cooldown: 55, StaminaCost: -1, HyperArmour: false, CounterSkill: true, IFrame: true, ClashPriority: 1, IsPure: false, SkillData: { Cooldown: 55, Power: 20, Range: 5, Speed: 1 } },
    Hardpoint: { DisplayName: "Hardpoint", Style: "Aikido", Cooldown: 30, StaminaCost: -1, ClashPriority: 1, SkillData: { Cooldown: 30, Power: 15, Range: 5, Speed: 1 } },
    WhirlwindSpin: { DisplayName: "Whirlwind Spin", Style: "Taekwondo", Cooldown: 30, StaminaCost: -1, HyperArmour: true, ClashPriority: 1, IsExtender: true, IsPure: true, SkillData: { Cooldown: 30, Power: 15, Range: 6, Speed: 1.15 } },
    Elbow_Cut: { DisplayName: "Elbow Cut", Style: "Kure", Cooldown: 38, StaminaCost: -1, ClashPriority: 2, IsExtender: true, SkillData: { Cooldown: 38, Power: 8.91, Range: 5, Speed: 1 } },
    Brute_Throw: { DisplayName: "Brute Throw", Style: "Reinhold", Cooldown: 58, StaminaCost: -1, GrabSkill: true, IFrame: true, ClashPriority: 1, SkillData: { Cooldown: 50, Power: 16.8, Range: 4, Speed: 1 } },
    Mountain_Breaker: { DisplayName: "Mountain_Breaker", Style: "Kure", Cooldown: 42, StaminaCost: -1, ClashPriority: 1, SkillData: { Cooldown: 42, Power: 8.6, Range: 5, Speed: 1.17 } },
    ChangeStance: { DisplayName: "Change Stance", Style: "Sumo", StaminaCost: -1, ClashPriority: 1, IgnoreOffensiveCheck: true, IsSkill: false, SkillData: { Cooldown: 0, Power: 0, Range: 0, Speed: 0 } },
    A_Just_Vengeance: { DisplayName: "A Just Vengeance", Style: "The_Middle", Cooldown: 40, StaminaCost: -1, HyperArmour: true, ClashPriority: 1, SkillData: { Cooldown: 40, Power: 18, Range: 5, Speed: 1 } },
    Right_Koken: { DisplayName: "Right Koken", Style: "Karate", Cooldown: 35, StaminaCost: -1, ClashPriority: 2, SkillData: { Cooldown: 35, Power: 15.3, Range: 6, Speed: 1 } },
    Knee_Strike: { DisplayName: "Knee Strike", Style: "Muay_Thai", Cooldown: 40, StaminaCost: -1, GrabSkill: true, IFrame: true, ClashPriority: 1, IsPure: true, SkillData: { Cooldown: 52, Power: 12.8, Range: 6, Speed: 1 } },
    Body_Sweep: { DisplayName: "Body Sweep", Style: "Aikido", Cooldown: 36, StaminaCost: -1, ClashPriority: 1, IsExtender: true, SkillData: { Cooldown: 36, Power: 18, Range: 5, Speed: 1 } },
    Gazelle_Punch: { DisplayName: "Gazelle Punch", Style: "BoxingLongGuard", Cooldown: 30, StaminaCost: -1, HyperArmour: true, ClashPriority: 2, SkillData: { Cooldown: 30, Power: 10.5, Range: 4.5, Speed: 1.25 } },
    Iron_Breaker: { DisplayName: "Iron Breaker", Style: "Niko", Cooldown: 33, StaminaCost: -1, ClashPriority: 2, IsExtender: true, SkillData: { Cooldown: 35, Power: 8.3, Range: 8, Speed: 1 } },
    Head_Slam: { DisplayName: "Head Slam", Style: "Taekwondo", Cooldown: 35, StaminaCost: -1, CounterSkill: true, IFrame: true, ClashPriority: 1, SkillData: { Cooldown: 35, Power: 17.64, Range: 6, Speed: 1 } },
    Binding_Hold: { DisplayName: "Binding Hold", Style: "Aikido", Cooldown: 30, StaminaCost: -1, CounterSkill: true, IFrame: true, ClashPriority: 1, SkillData: { Cooldown: 30, Power: 15.5, Range: 5, Speed: 1 } },
    MinotaurLeap: { DisplayName: "War Axe Slam", Cooldown: 0, StaminaCost: 0, ClashPriority: 999, IgnoreOffensiveCheck: true, Silenceable: false, SkillData: { Cooldown: 0, Power: 15, Range: 6, Speed: 1 } },
    Flying_Knee: { DisplayName: "Flying Knee", Style: "Muay_Thai", Cooldown: 37, StaminaCost: -1, ClashPriority: 1, SkillData: { Cooldown: 37, Power: 9, Range: 6, Speed: 1 } },
    Cranium_Break: { DisplayName: "Cranium Break", Style: "Demon_Fist", Cooldown: 50, StaminaCost: -1, GrabSkill: true, IFrame: true, ClashPriority: 1, SkillData: { Cooldown: 50, Power: 30, Range: 5, Speed: 1 } },
    Bulldoze: { DisplayName: "Bulldoze", Style: "Sumo", Cooldown: 45, StaminaCost: -1, ClashPriority: 1, SkillData: { Cooldown: 60, Power: 28.6, Range: 6, Speed: 1 } },
    Body_Drop: { DisplayName: "Body Drop", Style: "Sumo", Cooldown: 45, StaminaCost: -1, HyperArmour: true, ClashPriority: 1, SkillData: { Cooldown: 60, Power: 32.5, Range: 6, Speed: 1 } },
    Hammer_Palm: { DisplayName: "Hammer Palm", Style: "Reinhold", Cooldown: 40, StaminaCost: -1, ClashPriority: 1, SkillData: { Cooldown: 40, Power: 17.01, Range: 5, Speed: 1 } },
    Scissor_Sweep: { DisplayName: "Scissor Sweep", Style: "Jujutsu", Cooldown: 45, StaminaCost: -1, HyperArmour: false, GrabSkill: true, IFrame: true, ClashPriority: 1, IsPure: false, SkillData: { Cooldown: 45, Power: 15, Range: 5, Speed: 1 } },
    Flicker_Jab: { DisplayName: "Flicker Jab", Style: "BoxingLongGuard", Cooldown: 35, StaminaCost: -1, ClashPriority: 2, SkillData: { Cooldown: 35, Power: 13.2, Range: 6, Speed: 1 } },
    DivilJone_StrongRight: { DisplayName: "Strong Right", Cooldown: 0, StaminaCost: 0, ClashPriority: 999, IgnoreOffensiveCheck: true, Silenceable: false, SkillData: { Cooldown: 0, Power: 15, Range: 6, Speed: 1 } },
    MinotaurEnragedRoar: { DisplayName: "War Axe Slam", Cooldown: 0, StaminaCost: 0, ClashPriority: 999, IgnoreOffensiveCheck: true, Silenceable: false, SkillData: { Cooldown: 0, Power: 15, Range: 6, Speed: 1 } },
    DivilJone_Rampage: { DisplayName: "Rampage", Cooldown: 0, StaminaCost: 0, ClashPriority: 999, IgnoreOffensiveCheck: true, Silenceable: false, SkillData: { Cooldown: 0, Power: 15, Range: 6, Speed: 1 } },
    Jellyfish_Hold: { DisplayName: "Jellyfish Hold", Style: "Niko", Cooldown: 38, StaminaCost: -1, GrabSkill: true, ClashPriority: 2, SkillData: { Cooldown: 40, Power: 8, Range: 5, Speed: 1 } },
    WarAxeSlam: { DisplayName: "War Axe Slam", Cooldown: 0, StaminaCost: 0, ClashPriority: 999, IgnoreOffensiveCheck: true, Silenceable: false, SkillData: { Cooldown: 0, Power: 15, Range: 6, Speed: 1 } },
    Suplex: { DisplayName: "Suplex", Style: "Wrestling", Cooldown: 58, StaminaCost: -1, HyperArmour: true, GrabSkill: true, IFrame: true, ClashPriority: 1, IsPure: true, SkillData: { Cooldown: 60, Power: 21.48, Range: 6, Speed: 1 } },
    Tatsumaki: { DisplayName: "Tatsumaki", Style: "Street_Fighter", Cooldown: 44, StaminaCost: -1, ClashPriority: 2, IsExtender: true, SkillData: { Cooldown: 44, Power: 27, Range: 7, Speed: 1 } },
    MinotaurStomp: { DisplayName: "War Axe Slam", Cooldown: 0, StaminaCost: 0, ClashPriority: 999, IgnoreOffensiveCheck: true, Silenceable: false, SkillData: { Cooldown: 0, Power: 15, Range: 6, Speed: 1 } },
    Dream_Walking: { DisplayName: "Dream Walking", Style: "Raishin", Cooldown: 50, StaminaCost: -1, CounterSkill: true, IFrame: true, ClashPriority: 1, SkillData: { Cooldown: 50, Power: 15.75, Range: 5, Speed: 1 } },
    MinotaurPunch: { DisplayName: "War Axe Slam", Cooldown: 0, StaminaCost: 0, ClashPriority: 999, IgnoreOffensiveCheck: true, Silenceable: false, SkillData: { Cooldown: 0, Power: 15, Range: 6, Speed: 1 } },
    OneTwo: { DisplayName: "One-Two", Style: "Boxing", Cooldown: 8, StaminaCost: -1, SkillData: { Cooldown: 0, Power: 0, Range: 0, Speed: 0 } },
    MinotaurRoar: { DisplayName: "War Axe Slam", Cooldown: 0, StaminaCost: 0, ClashPriority: 999, IgnoreOffensiveCheck: true, Silenceable: false, SkillData: { Cooldown: 0, Power: 15, Range: 6, Speed: 1 } },
    Devil_Lance: { DisplayName: "Devil Lance", Style: "Karate", Cooldown: 36, StaminaCost: -1, ClashPriority: 1, IsExtender: true, IsPure: true, SkillData: { Cooldown: 36, Power: 12, Range: 6, Speed: 1 } },
    Palm_Bomb: { DisplayName: "Palm Bomb", Style: "Aikido", Cooldown: 42, StaminaCost: -1, ClashPriority: 1, SkillData: { Cooldown: 35, Power: 13, Range: 5, Speed: 1 } },
    MinotaurCharge: { DisplayName: "War Axe Slam", Cooldown: 0, StaminaCost: 0, ClashPriority: 999, IgnoreOffensiveCheck: true, Silenceable: false, SkillData: { Cooldown: 0, Power: 15, Range: 6, Speed: 1 } },
    Hyakuretsukyaku: { DisplayName: "Hyakuretsukyaku", Style: "Street_Fighter", Cooldown: 40, StaminaCost: -1, ClashPriority: 1, SkillData: { Cooldown: 40, Power: 20.93, Range: 5, Speed: 1 } },
    Feinting_Elbow: { DisplayName: "Feinting Elbow", Style: "Karate", Cooldown: 30, StaminaCost: -1, IFrame: true, ClashPriority: 2, SkillData: { Cooldown: 30, Power: 15.2, Range: 6, Speed: 1.1 } },
    Liver_Blow: { DisplayName: "Liver Blow", Style: "Boxing", Cooldown: 32, StaminaCost: -1, ClashPriority: 2, IsExtender: true, SkillData: { Cooldown: 25, Power: 10.2, Range: 4, Speed: 1.1 } },
    Ravage: { DisplayName: "Ravage", Style: "KJ", Cooldown: 60, StaminaCost: -1, GrabSkill: true, IFrame: true, ClashPriority: 1, SkillData: { Cooldown: 60, Power: 25, Range: 6, Speed: 1.15 } },
    Earth_Shatter: { DisplayName: "Earth Shatter", Style: "Demon_Fist", Cooldown: 48, StaminaCost: -1, ClashPriority: 1, SkillData: { Cooldown: 48, Power: 10.5, Range: 5, Speed: 1 } },
    Neck_Breaker: { DisplayName: "Neck Breaker", Style: "Niko", Cooldown: 42, StaminaCost: -1, CounterSkill: true, ClashPriority: 2, SkillData: { Cooldown: 45, Power: 10, Range: 8, Speed: 1 } },
    Bear_Hug: { DisplayName: "Bear Hug", Style: "Reinhold", Cooldown: 56, StaminaCost: -1, GrabSkill: true, IFrame: true, ClashPriority: 1, SkillData: { Cooldown: 50, Power: 19, Range: 4.3, Speed: 1 } },
    Roundhouse_Kick: { DisplayName: "Roundhouse Kick", Style: "Muay_Thai", Cooldown: 27, StaminaCost: -1, ClashPriority: 1, IsExtender: true, SkillData: { Cooldown: 27, Power: 9.6, Range: 6, Speed: 1.1 } },
    DivilJone_Orbital: { DisplayName: "Orbital", Cooldown: 0, StaminaCost: 0, ClashPriority: 999, IgnoreOffensiveCheck: true, Silenceable: false, SkillData: { Cooldown: 0, Power: 15, Range: 6, Speed: 1 } },
    Lion_Bite: { DisplayName: "Lion's Bite", Style: "Kure", Cooldown: 40, StaminaCost: -1, GrabSkill: true, ClashPriority: 1, IsExtender: true, SkillData: { Cooldown: 35, Power: 14, Range: 35, Speed: 1.2 } },
    Flying_Side_Kick: { DisplayName: "Flying Side Kick", Style: "Taekwondo", Cooldown: 33, StaminaCost: -1, ClashPriority: 1, SkillData: { Cooldown: 33, Power: 14, Range: 6, Speed: 1 } },
    Counter_Cut: { DisplayName: "Counter Cut", Style: "Boxing", Cooldown: 40, StaminaCost: -1, CounterSkill: true, IFrame: true, ClashPriority: 1, SkillData: { Cooldown: 40, Power: 10.24, Range: 6, Speed: 1 } },
    Pure_Taekwondo: { DisplayName: "Pure Taekwondo", Style: "Taekwondo", Cooldown: 22, StaminaCost: -1, GrabSkill: true, IFrame: true, ClashPriority: 1, SkillData: { Cooldown: 0, Power: 0, Range: 0, Speed: 0 } },
    Six_Seiken: { DisplayName: "Six Seiken", Style: "Karate", Cooldown: 30, StaminaCost: -1, ClashPriority: 2, SkillData: { Cooldown: 30, Power: 15.86, Range: 6, Speed: 1 } },
    Russian_Tie: { DisplayName: "Russian Tie", Style: "Jujutsu", Cooldown: 42, StaminaCost: -1, HyperArmour: false, GrabSkill: true, IFrame: true, ClashPriority: 1, IsPure: false, SkillData: { Cooldown: 42, Power: 15, Range: 5, Speed: 1 } },
    Predictive_Strikes: { DisplayName: "Predictive Strikes", Style: "Demon_Fist", Cooldown: 50, StaminaCost: -1, CounterSkill: true, ClashPriority: 1, SkillData: { Cooldown: 35, Power: 25, Range: 6, Speed: 1 } },
    StarDrop: { DisplayName: "Star Drop", Style: "Aikido", Cooldown: 30, StaminaCost: -1, CounterSkill: true, IFrame: true, ClashPriority: 1, SkillData: { Cooldown: 30, Power: 16.5, Range: 5, Speed: 1 } },
    Spinning_Backfist: { DisplayName: "Spinning Backfist", Style: "Kickboxing", Cooldown: 60, StaminaCost: -1, ClashPriority: 1, SkillData: { Cooldown: 35, Power: 12.24, Range: 6, Speed: 1 } },
    Swift_Kick: { DisplayName: "Swift Kick", Style: "Kickboxing", Cooldown: 36, StaminaCost: -1, ClashPriority: 1, IsExtender: true, SkillData: { Cooldown: 35, Power: 14.4, Range: 6, Speed: 1.3 } },
    Oblique_Kick: { DisplayName: "Oblique Kick", Style: "Kickboxing", Cooldown: 36, StaminaCost: -1, ClashPriority: 1, IsExtender: true, SkillData: { Cooldown: 35, Power: 14, Range: 6, Speed: 1.5 } },
    Flashing_Steel: { DisplayName: "Flashing  Steel", Style: "Niko", Cooldown: 40, StaminaCost: -1, CounterSkill: true, ClashPriority: 2, SkillData: { Cooldown: 40, Power: 14, Range: 5, Speed: 1 } },
    Ear_Clap: { DisplayName: "Ear Clap", Style: "Demon_Fist", Cooldown: 44, StaminaCost: -1, ClashPriority: 1, IsExtender: true, SkillData: { Cooldown: 44, Power: 13, Range: 5, Speed: 1.15 } },
    Elbow_Smash: { DisplayName: "Elbow Smash", Style: "Aikido", Cooldown: 45, StaminaCost: -1, GrabSkill: true, IFrame: true, ClashPriority: 1, SkillData: { Cooldown: 45, Power: 16.5, Range: 5, Speed: 1 } },
    Rock_Punch: { DisplayName: "Rock Punch", Style: "Reinhold", Cooldown: 75, StaminaCost: -1, HyperArmour: true, ClashPriority: 1, IsPure: true, SkillData: { Cooldown: 90, Power: 22.275, Range: 5, Speed: 1 } },
    Garuda_Fang: { DisplayName: "Garuda_Fang", Style: "Muay_Thai", Cooldown: 35, StaminaCost: -1, ClashPriority: 1, SkillData: { Cooldown: 35, Power: 9, Range: 6, Speed: 1 } },
    Blazing_Dragon: { DisplayName: "Blazing Dragon", Style: "Street_Fighter", Cooldown: 35, StaminaCost: -1, ClashPriority: 2, SkillData: { Cooldown: 35, Power: 20, Range: 8, Speed: 1 } },
    DivilJoneRoar: { DisplayName: "Roar", Cooldown: 0, StaminaCost: 0, ClashPriority: 999, IgnoreOffensiveCheck: true, Silenceable: false, SkillData: { Cooldown: 0, Power: 15, Range: 6, Speed: 1 } },
    Shoryuken: { DisplayName: "Shoryuken", Style: "Street_Fighter", Cooldown: 44, StaminaCost: -1, ClashPriority: 2, MissEndlag: 0.9, SkillData: { Cooldown: 35, Power: 16, Range: 7, Speed: 1 } },
    Hadouken: { DisplayName: "Hadouken", Style: "Street_Fighter", Cooldown: 40, StaminaCost: -1, ClashPriority: 1, SkillData: { Cooldown: 40, Power: 16.5, Range: 6, Speed: 1 } },
    Weeping_Willow: { DisplayName: "Weeping Willow", Style: "Niko", Cooldown: 36, StaminaCost: -1, CounterSkill: true, IFrame: true, ClashPriority: 1, SkillData: { Cooldown: 30, Power: 8.125, Range: 5, Speed: 1 } },
    Thunderclap: { DisplayName: "Thunderclap", Style: "Raishin", Cooldown: 38, StaminaCost: -1, ClashPriority: 1, SkillData: { Cooldown: 38, Power: 11.18, Range: 5, Speed: 1 } },
    Cascade: { DisplayName: "Cascade", Style: "Raishin", Cooldown: 38, StaminaCost: -1, GrabSkill: true, IFrame: true, ClashPriority: 1, SkillData: { Cooldown: 38, Power: 6.175, Range: 5, Speed: 1 } },
    Sit_Through: { DisplayName: "Sit Through", Style: "Jujutsu", Cooldown: 42, StaminaCost: -1, HyperArmour: false, GrabSkill: true, IFrame: true, ClashPriority: 1, IsPure: false, SkillData: { Cooldown: 42, Power: 14, Range: 5, Speed: 1 } },
    Palm_Barrage: { DisplayName: "Palm Barrage", Style: "Sumo", Cooldown: 45, StaminaCost: -1, ClashPriority: 1, SkillData: { Cooldown: 60, Power: 29.9, Range: 6, Speed: 1 } },
    Block: { DisplayName: "Block", Style: "", Cooldown: 0.5, StaminaCost: 0, HyperArmour: false, GrabSkill: false, CounterSkill: false, IFrame: false, ClashPriority: 1, Silenceable: true, Clashable: false, IsSkill: false, SkillData: { Cooldown: { Base: 60, Affect: { Power: -0.12, Speed: -0.14, PerUpgrade: -0.04, ScaleBy: 1.25 } }, Power: { Base: 29.5, Affect: { Speed: 0.25, Cooldown: -0.22, PerUpgrade: 0.045, ScaleBy: 1.1 } }, Range: { Base: 6, Affect: { Power: 0.1, PerUpgrade: 0.04, ScaleBy: 1.15 } }, Speed: { Base: 1.5, Affect: { Power: 0.1, Cooldown: -0.17, PerUpgrade: 0.07, ScaleBy: 1.5 } } }, Stages: { Slam: { DamageRatio: 1, Stun: 0.75, Ragdoll: 2.3, Blockbreak: true, IFrame: true } }, IgnoreLevel: 0 },
    Avidya: { DisplayName: "Avidyā", Style: "Kure", Cooldown: 32, StaminaCost: -1, ClashPriority: 2, SkillData: { Cooldown: 35, Power: 9.45, Range: 5, Speed: 1 } },
    Kicking: { DisplayName: "Kicking", Style: "The_Middle", Cooldown: 40, StaminaCost: -1, ClashPriority: 1, SkillData: { Cooldown: 40, Power: 18.2, Range: 5, Speed: 1 } },
    Cleaving_Fang: { DisplayName: "Cleaving Fang", Style: "Taekwondo", Cooldown: 40, StaminaCost: -1, GrabSkill: true, IFrame: true, ClashPriority: 1, SkillData: { Cooldown: 54, Power: 14.96, Range: 6, Speed: 1.5 } },
    Shockwave_Palm: { DisplayName: "Shockwave Palm", Style: "Aikido", Cooldown: 45, StaminaCost: -1, ClashPriority: 1, SkillData: { Cooldown: 40, Power: 14, Range: 5, Speed: 1 } },
    Whirl_Slam: { DisplayName: "Whirl Slam", Style: "Wrestling", Cooldown: 46, StaminaCost: -1, GrabSkill: true, IFrame: true, ClashPriority: 1, SkillData: { Cooldown: 60, Power: 17.85, Range: 6, Speed: 1.5 } },
    ElbowDrop: { DisplayName: "Elbow Drop", Style: "Wrestling", Cooldown: 50, StaminaCost: -1, HyperArmour: true, ClashPriority: 1, SkillData: { Cooldown: 60, Power: 21.15, Range: 6, Speed: 1.2375 } },
    Rushing_Kick: { DisplayName: "Rushing Kick", Style: "Taekwondo", Cooldown: 35, StaminaCost: -1, ClashPriority: 1, SkillData: { Cooldown: 35, Power: 14, Range: 6, Speed: 1 } },
    Promised_Suffering: { DisplayName: "Promised Suffering", Style: "The_Middle", Cooldown: 50, StaminaCost: -1, GrabSkill: true, IFrame: true, ClashPriority: 1, SkillData: { Cooldown: 50, Power: 22, Range: 4.5, Speed: 1 } },
    Crushing_Throw: { DisplayName: "Crushing Throw", Style: "Sumo", Cooldown: 45, StaminaCost: -1, HyperArmour: true, GrabSkill: true, IFrame: true, ClashPriority: 1, IsPure: true, SkillData: { Cooldown: 60, Power: 31.2, Range: 6, Speed: 1 } },
    Raging_Elbow: { DisplayName: "Raging_Elbow", Style: "Muay_Thai", Cooldown: 35, StaminaCost: -1, ClashPriority: 1, SkillData: { Cooldown: 35, Power: 8.8, Range: 6, Speed: 1 } },
    Spinning_Elbow: { DisplayName: "Spinning Elbow", Style: "Muay_Thai", Cooldown: 38, StaminaCost: -1, HyperArmour: true, ClashPriority: 1, SkillData: { Cooldown: 38, Power: 9.25, Range: 6, Speed: 1 } },
    Triple_Kick: { DisplayName: "Triple Kick", Style: "Taekwondo", Cooldown: 30, StaminaCost: -1, ClashPriority: 1, SkillData: { Cooldown: 30, Power: 15, Range: 6, Speed: 0.8 } },
    Rolling: { DisplayName: "Rolling", Style: "Kickboxing", Cooldown: 40, StaminaCost: -1, ClashPriority: 1, SkillData: { Cooldown: 35, Power: 17.2, Range: 6, Speed: 1.4 } },
    Questionmark_Kick: { DisplayName: "Question Mark Kick", Style: "Taekwondo", Cooldown: 35, StaminaCost: -1, ClashPriority: 1, IsExtender: true, SkillData: { Cooldown: 35, Power: 12, Range: 6, Speed: 1.1 } },
    MaDeedKalok: { DisplayName: "Ma Deed Kalok", Style: "Muay_Thai", Cooldown: 40, StaminaCost: -1, GrabSkill: true, IFrame: true, ClashPriority: 1, IsExtender: true, SkillData: { Cooldown: 32, Power: 7.8, Range: 6, Speed: 1.5 } },
    Write_em_all_down: { DisplayName: "Write 'em All Down", Style: "The_Middle", Cooldown: 47, StaminaCost: -1, ClashPriority: 1, SkillData: { Cooldown: 47, Power: 18, Range: 10, Speed: 1.1 } },
    Double_Kick: { DisplayName: "Double Kick", Style: "Taekwondo", Cooldown: 34, StaminaCost: -1, ClashPriority: 1, IsExtender: true, SkillData: { Cooldown: 34, Power: 12, Range: 6, Speed: 1 } },
    Payback: { DisplayName: "Payback", Style: "The_Middle", Cooldown: 38, StaminaCost: -1, HyperArmour: true, ClashPriority: 1, IsExtender: true, SkillData: { Cooldown: 38, Power: 13.8, Range: 5, Speed: 1 } },
    // Removed 2026-08-18: phantom duplicate of Elbow_Cut from the old typo key,
    // carrying the wrong style (Muay_Thai vs the live Kure) and pre-rework values.
  },
  // Hits + total damage-ratio multiplier per skill, read from the live
  // SkillReg.<Skill> modules (Stages + FinalDamage/DealDamage usage; hit-count
  // source of truth). hits = DealDamage applications per Activate, sum = total
  // damage-ratio multiplier dealt (Σ per application). Total skill damage = per-hit
  // damage × sum. The "hits" override in the UI simulates N hits of DamageRatio 1 each.
  stageData: {
    Steel_Blast:       { hits: 1, sum: 1 },
    Flash_Fire:        { hits: 1, sum: 1 },
    ChokeSlam:         { hits: 1, sum: 1 },
    Nerve_Strike:      { hits: 1, sum: 0.5 },
    Lightning_Flash:   { hits: 1, sum: 1 },
    Rising_Heel:       { hits: 1, sum: 1 },
    ElbowDrop:         { hits: 1, sum: 1 },
    Avidya:            { hits: 1, sum: 1 },
    Elbow_Cut:         { hits: 1, sum: 1 },
    Brute_Throw:       { hits: 3, sum: 1 },
    Mountain_Breaker:  { hits: 3, sum: 3 },
    A_Just_Vengeance:  { hits: 3, sum: 0.875 },
    Right_Koken:       { hits: 1, sum: 1 },
    Knee_Strike:       { hits: 3, sum: 0.373611 },
    Weeping_Willow:    { hits: 1, sum: 1 },
    Gazelle_Punch:     { hits: 1, sum: 1 },
    Iron_Breaker:      { hits: 1, sum: 1 },
    Head_Slam:         { hits: 2, sum: 1 },
    Binding_Hold:      { hits: 1, sum: 1 },
    Flying_Knee:       { hits: 1, sum: 1 },
    Cranium_Break:     { hits: 3, sum: 0.75 },
    Bulldoze:          { hits: 1, sum: 1 },
    Body_Drop:         { hits: 1, sum: 1 },
    Hammer_Palm:       { hits: 1, sum: 1 },
    Flicker_Jab:       { hits: 1, sum: 0.111111 },
    Suplex:            { hits: 1, sum: 1 },
    Blazing_Dragon:    { hits: 1, sum: 1 },
    Dream_Walking:     { hits: 1, sum: 1 },
    Write_em_all_down: { hits: 1, sum: 1 },
    Hyakuretsukyaku:   { hits: 5, sum: 0.6 },
    Spinning_Elbow:    { hits: 1, sum: 1 },
    Payback:           { hits: 1, sum: 1 },
    Liver_Blow:        { hits: 1, sum: 1 },
    Earth_Shatter:     { hits: 1, sum: 1 },
    Bear_Hug:          { hits: 2, sum: 1 },
    Roundhouse_Kick:   { hits: 1, sum: 1 },
    Lion_Bite:         { hits: 1, sum: 0.7 },
    Flying_Side_Kick:  { hits: 1, sum: 1 },
    Counter_Cut:       { hits: 1, sum: 1 },
    Pure_Taekwondo:    { hits: 1, sum: 0.5 },
    Six_Seiken:        { hits: 3, sum: 0.7597 },
    StarDrop:          { hits: 1, sum: 1 },
    Swift_Kick:        { hits: 1, sum: 1 },
    Ear_Clap:          { hits: 1, sum: 1 },
    Russian_Tie:       { hits: 1, sum: 1 },
    Rock_Punch:        { hits: 1, sum: 1 },
    Whirl_Slam:        { hits: 1, sum: 1 },
    Garuda_Fang:       { hits: 2, sum: 1 },
    Cascade:           { hits: 4, sum: 4 },
    OneTwo:            { hits: 2, sum: 1 },
    Hadouken:          { hits: 1, sum: 1 },
    Oblique_Kick:      { hits: 1, sum: 1 },
    Shoryuken:         { hits: 1, sum: 1 },
    MaDeedKalok:       { hits: 1, sum: 1 },
    Sit_Through:       { hits: 1, sum: 1 },
    Palm_Barrage:      { hits: 2, sum: 0.097619 },
    Ravage:            { hits: 5, sum: 0.598485 },
    Devil_Lance:       { hits: 1, sum: 1 },
    Promised_Suffering: { hits: 2, sum: 1 },
    Cleaving_Fang:     { hits: 2, sum: 0.333333 },
    Rushing_Kick:      { hits: 2, sum: 1 },
    Feinting_Elbow:    { hits: 1, sum: 1 },
    Hardpoint:         { hits: 1, sum: 1 },
    WhirlwindSpin:     { hits: 1, sum: 1 },
    Predictive_Strikes: { hits: 3, sum: 1 },
    Crushing_Throw:    { hits: 1, sum: 1 },
    Raging_Elbow:      { hits: 1, sum: 1 },
    Tatsumaki:         { hits: 1, sum: 0.25 },
    Triple_Kick:       { hits: 3, sum: 1 },
    Rolling:           { hits: 1, sum: 1 },
    Questionmark_Kick: { hits: 1, sum: 1 },
    Thunderclap:       { hits: 3, sum: 0.576316 },
    Spinning_Backfist: { hits: 1, sum: 1 },
    Double_Kick:       { hits: 2, sum: 1 },
    Kicking:           { hits: 3, sum: 1 },
    Anaconda_Choke:    { hits: 1, sum: 1 },
    Body_Sweep:        { hits: 1, sum: 0.5 },
    Scissor_Sweep:     { hits: 2, sum: 1 },
    Jellyfish_Hold:    { hits: 2, sum: 1 },
    Palm_Bomb:         { hits: 2, sum: 1 },
    Neck_Breaker:      { hits: 1, sum: 1 },
    Flashing_Steel:    { hits: 1, sum: 1 },
    Elbow_Smash:       { hits: 3, sum: 1 },
    Shockwave_Palm:    { hits: 1, sum: 1 },
  },
  // For bot-only skills that lack a style mapping, fall back to this when computing
  skillStatsForBots: {
    Lightning_Flash: { Power: 20, Cooldown: 1, Range: 20, Speed: 1 },
    Lion_Bite:       { Power: 20, Cooldown: 1, Range: 20, Speed: 1 },
  },

  // Style display order + grouping used by the UI
  styleOrder: [
    "Basic", "Kung_Fu", "Aikido", "Jujutsu", "The_Middle", "Kure", "Raishin",
    "Sumo", "Taekwondo", "Kickboxing", "Sky", "Zhin", "Cat", "Kujin", "Kazu",
    "WarAxe", "Grand-WarAxe", "BoxingLongGuard", "Muay_Thai", "Wrestling",
    "Karate", "Niko", "Reinhold", "Demon_Fist", "Ya", "Yuzuki-no-Mai",
  ],
};
